### ISSUE TITLE
Support for PANOX V2

### ISSUE THREAD

**Issue by dnzeek** [labpano/pilot-control-protocol#4]
@zero-zzxx 

Hi. Can this protocol be used with the PANOX V2 camera? If not, is there another one that can be used from PC?

Thank you.

**Comment by zero-zzxx** [comment]
The documentation here is not suitable for connecting to PANOX V2 camera.
The documentation for PANOX V2 is currently being compiled and there are some differences from this document. If necessary, you can contact technical support to obtain internal documentation. External documentation will also be released as soon as possible, but it will take time.
There is no difference in accessing from a computer or other.

**Comment by dnzeek** [comment]
Thank you. I sent a request to support@labpano.com
