### ISSUE TITLE
Can't query command status

### ISSUE THREAD

**Issue by flyingdove** [labpano/pilot-control-protocol#5]
Hello,

Camera: Panox V2.

Can't get how to request command status after takePicture command. Camera responds with 401 Unathorized.

I've attached screenshorts. Thank you.

![Take Picture](https://github.com/user-attachments/assets/45d39828-6fd9-44d7-90dc-a8c09c0e2a27)
![Query Status](https://github.com/user-attachments/assets/42ef8d4a-0923-4bd4-b57c-10d08f413edc)

**Comment by zero-zzxx** [comment]
The 'pilot control protocol' is not applicable to PanoX V2 devices.

**Comment by zero-zzxx** [comment]
For information on connecting to the PanoX V2 control, please contact support@labpano.com.
